### ISSUE TITLE
nether does not load chunks

### ISSUE THREAD

**Issue by feanchy** [KCodeYT/VanillaGenerator#10] opened 2022-06-18 20:28 UTC
#Error error report
chunks in nether are not loade
![174149868-20d0b1e7-05f3-4917-9412-1aad9b73a573](https://user-images.githubusercontent.com/50043944/174456139-0204e239-5214-4452-ab4c-3e777309f2cc.png)

 (and so it is everywhere)

###Other information
I tried deleting the world and restarting the server, it doesn't help

**Comment by KCodeYT** [comment] 2022-06-19 03:24
This issue is already known to me and Im currently trying to fix this, but it can take time as its not as easy to fix as it looks, so sorry.

**Comment by KCodeYT** [comment] 2022-06-19 04:48
Duplicate of #6, closing this issue.
Follow #6.

Still thanks for helping out!

**Closed as not planned by KCodeYT** 2022-06-19 04:48 UTC

**Comment by feanchy** [comment] 2022-06-19 12:14
> Дубликат [№ 6](https://github.com/KCodeYT/VanillaGenerator/issues/6) , закрывая этот вопрос. Следуйте [№ 6](https://github.com/KCodeYT/VanillaGenerator/issues/6) .
> 
> Все равно спасибо за помощь!

thank you for your patience
